Repository AY2425S1-CS2103-F12-2/tp, pull requests merged in 2024-10, with the labels that each got.

#26 Update DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: priority.High

#34 Update readme.md and dg
  README.md
  docs/DeveloperGuide.md
  docs/index.md
Labels: type.Bug

#40 Fix checkstyle
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#49 Refactored DeleteCommand to DeleteStudentCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
Labels: type.Story, priority.High

#62 Add Task class
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskName.java
Labels: type.Enhancement, priority.High

#82 Update gui list tasks
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: type.Task, priority.High

#93 Testcase for delete student from group
  src/main/java/seedu/address/logic/commands/DeleteStudentFromGroupCommand.java
  src/main/java/seedu/address/model/group/exception/GroupNotFoundException.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteStudentFromGroupCommandParserTest.java
Labels: priority.High

#91 Add test cases for components of Task class
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/model/task/StatusTest.java
  src/test/java/seedu/address/model/task/TaskNameTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High

#94 List tasks command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/ui/GroupTaskCard.java
  src/main/java/seedu/address/ui/GroupTaskPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/GroupTaskCard.fxml
Labels: type.Story, priority.High

#95 List all tasks command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
Labels: type.Story, priority.High

#98 Re-implement delete group function
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/group/exception/GroupNotFoundException.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/ui/GroupTaskPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
Labels: type.Story, type.Enhancement, priority.High

#105 Added TaskTest + Fix errant test cases due to update in Email validation
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/student/EmailTest.java
  src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.High

#111 Fix gui bugs
  src/main/java/seedu/address/logic/commands/AddTaskToGroupCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/GroupTaskCard.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.Medium

#110 Update link in help command
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.Low, severity.Low

#112 Add basic test cases for Delete Group Command
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
Labels: type.Enhancement, priority.Medium

#121 Update Save/Load feature + Student Class
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/GroupTaskCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High, severity.High

#126 Fix test cases for delete student from group command
  src/main/java/seedu/address/logic/commands/DeleteStudentFromGroupCommand.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
Labels: priority.High

#128 Update student optional parameter, task list now updates when deleting a group
  src/main/java/seedu/address/logic/commands/AddStudentToGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
Labels: type.Enhancement, priority.Medium

#131 Fix AddressBook not saving student with updated GroupName attribute
  src/main/java/seedu/address/model/AddressBook.java
Labels: type.Bug

#134 V1.3 prep
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/data/JsonSerializableAddressBookTest/duplicateGroupAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidGroupAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalGroupAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: priority.High, severity.High

#143 Update COMMAND_WORD and Add COMMAND_WORD_ALIAS
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentToGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/ListGroupCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#159 Enable assertions and import FuzzyWuzzy
  build.gradle
Labels: priority.High, severity.High

#154 Edit group function
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditGroupCommandParser.java
  src/test/java/seedu/address/logic/commands/EditGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditGroupCommandParserTest.java
Labels: priority.High

#150 Implement edit student command
  src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java
  src/main/java/seedu/address/logic/parser/editcommands/EditStudentCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditStudentCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#160 Fix gradle issues post cleanup
  src/main/java/seedu/address/logic/commands/editcommands/EditGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommands/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, severity.Low

#145 Undo redo command v2
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddStudentToGroupCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteStudentFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteTaskFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListGroupCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListStudentCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/versionhistorycommands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/versionhistorycommands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/VersionHistory.java
  src/main/java/seedu/address/model/exceptions/RedoLimitException.java
  src/main/java/seedu/address/model/exceptions/UndoLimitException.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonSerializableVersionHistory.java
  src/main/java/seedu/address/storage/JsonVersionHistoryStorage.java
  src/main/java/seedu/address/storage/VersionHistoryStorage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  versionhistory.json
Labels: type.Enhancement, priority.Medium

#163 Update SampleDataUtil to suit our current data format
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement, priority.Low, severity.Low

#168 Add Find Student Command + Test Cases
  src/main/java/seedu/address/logic/commands/findcommands/FindStudentCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/findcommands/FindStudentCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/student/StudentMatchesQueryPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/FindStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindStudentCommandParserTest.java
  src/test/java/seedu/address/model/student/StudentMatchesKeywordPredicateTest.java
Labels: type.Enhancement, priority.High, severity.High

#167 Implement Sort Feature
  src/main/java/seedu/address/logic/commands/sortcommands/SortGroupCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortStudentCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/sortcommands/SortGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/sortcommands/SortStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/sortcommands/SortTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
  versionhistory.json
Labels: priority.High

#169 Add FindGroupCommand + test cases
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/findcommands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/findcommands/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommands/FindGroupCommandParser.java
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/group/GroupNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/FindGroupCommandParserTest.java
  src/test/java/seedu/address/model/group/GroupNameContainsKeywordsPredicateTest.java
Labels: type.Story, type.Enhancement, priority.High, severity.Medium

#171 Add find task command + test cases
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/findcommands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/findcommands/FindTaskCommandParser.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story, type.Enhancement, priority.High, severity.Medium

#173 Enable text wrap for result display
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low, severity.VeryLow

#174 Post merge fixes
  .gitignore
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  versionhistory.json
Labels: priority.High

#200 Fix LOD errors
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/group/GroupNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/StudentMatchesQueryPredicate.java
  src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
Labels: priority.High, severity.Medium

#197 Update command word matching to be case-insensitive
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.High, severity.Medium, alpha-bug

#198 Update necessary equals methods to ignoreCase
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: priority.High, severity.High, alpha-bug
