Repository AY2425S1-CS2103-F12-2/tp, pull requests merged in 2024-11, with the labels that each got.

#224 Allow case insensitive input and edit command messages
  src/main/java/seedu/address/logic/commands/addcommands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortGroupCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortStudentCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortTaskCommand.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/StudentNumber.java
Labels: priority.High, alpha-bug

#235 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  docs/index.md
Labels: type.Task, priority.High

#236 Update Command notes
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#227 Updates on the following features and bugs
  src/main/java/seedu/address/logic/ListMarkers.java
  src/main/java/seedu/address/logic/commands/addcommands/AddExistingTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddStudentToGroupCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddTaskToAllGroupsCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteStudentFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteTaskFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskAllGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindStudentCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListGroupCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListStudentCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/markcommands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortGroupCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortStudentCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortTaskCommand.java
  src/main/java/seedu/address/logic/commands/versionhistorycommands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/versionhistorycommands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddExistingTaskToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddStudentToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddTaskToAllGroupsCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddTaskToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteStudentFromGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteTaskFromGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditTaskAllGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/markcommands/MarkTaskCommandParser.java
Labels: priority.High, severity.High, alpha-bug

#239 Set up template for UG
  docs/AboutUs.md
  docs/UserGuide.md
Labels: priority.High, severity.High

#243 Set up templates for UG and DG + update user stories
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/request_access.png
  docs/images/screenshots/add_student.png
  docs/images/screenshots/findAlexDavidResult.png
  docs/images/screenshots/helpMessage.png
  docs/images/screenshots/list_students.png
Labels: type.Enhancement, priority.High, severity.High

#241 Update Find Commands to use strict matching and update access modifiers of fields
  build.gradle
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/addcommands/AddTaskToAllGroupsCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteTaskFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindStudentCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/markcommands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortGroupCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortStudentCommand.java
  src/main/java/seedu/address/logic/parser/findcommands/FindStudentCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/group/GroupNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/StudentMatchesQueryPredicate.java
  src/main/java/seedu/address/model/student/StudentNumber.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/cards/GroupCard.java
  src/main/java/seedu/address/ui/cards/GroupTaskCard.java
  src/main/java/seedu/address/ui/cards/PersonCard.java
  src/main/java/seedu/address/ui/cards/TaskCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/FindStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindStudentCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/group/GroupNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/StudentMatchesKeywordPredicateTest.java
  src/test/java/seedu/address/model/task/TaskNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Bug, priority.High, severity.High, alpha-bug

#252 Updates on my parts in the UG
  docs/UserGuide.md
  docs/images/screenshots/add_et_g.png
  docs/images/screenshots/add_et_g_err.png
  docs/images/screenshots/del_g.png
  docs/images/screenshots/find_g.png
  docs/images/screenshots/find_s.png
  docs/images/screenshots/find_s_nogroup.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/findcommands/FindStudentCommand.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/test/java/seedu/address/logic/commands/FindStudentCommandTest.java
Labels: type.Enhancement, priority.High

#272 20241105 Fix bugs + enhancements
  src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/task/Deadline.java
Labels: type.Enhancement, type.Bug, priority.High, severity.High, alpha-bug

#274 20241105 ug updates
  docs/UserGuide.md
Labels: type.Documentation

#285 20241105 dg updates
  docs/DeveloperGuide.md
  docs/diagrams/DeleteGroupSequenceDiagram.puml
Labels: alpha-bug, type.Documentation

#292 20241106 ugdg updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteGroupActivityDiagram.puml
  docs/diagrams/DeleteGroupSequenceDiagram.puml
Labels: type.Documentation

#282 Implement user guide for student command features
  docs/UserGuide.md
  docs/images/screenshots/add_s_g.png
  docs/images/screenshots/del_s.png
  docs/images/screenshots/del_s_g.png
  docs/images/screenshots/edit_s.png
  docs/images/screenshots/sort_s.png
Labels: priority.High, type.Documentation

#294 Update edit_s feature
  docs/UserGuide.md
Labels: alpha-bug, type.Documentation

#295 Fix bugs and enhancements
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/addcommands/AddExistingTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddStudentToGroupCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddTaskToAllGroupsCommand.java
  src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteStudentFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteTaskForAllGroupsCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteTaskFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskAllGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/markcommands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortGroupCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortStudentCommand.java
  src/main/java/seedu/address/logic/commands/sortcommands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteStudentFromGroupCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/ui/cards/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteStudentFromGroupCommandParserTest.java
Labels: priority.High, severity.High

#298 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: priority.High

#299 Update sidenav
  docs/_markbind/layouts/default.md
Labels: type.Documentation

#301 Update input validation and command parameters
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/addcommands/AddStudentToGroupCommand.java
  src/main/java/seedu/address/logic/parser/addcommands/AddStudentToGroupCommandParser.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentNumber.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/student/EmailTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: type.Enhancement, type.Bug, priority.High, type.Documentation

#308 20241107 documentation updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/addcommands/AddTaskToGroupCommandParser.java
Labels: type.Bug, priority.High, severity.High, alpha-bug, type.Documentation

#309 Update version to 1.5
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#310 Change log level back to INFO
  src/main/java/seedu/address/commons/core/Config.java
Labels: type.Task

#313 Add section
  docs/DeveloperGuide.md
Labels: type.Documentation

#316 20241107 documentation updates
  docs/UserGuide.md
Labels: type.Documentation

#317 Update email constraints
  docs/UserGuide.md
Labels: type.Documentation

#314 V1.5 prep
  src/main/java/seedu/address/logic/commands/addcommands/AddStudentToGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/versionhistorycommandparser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/versionhistorycommandparser/UndoCommandParser.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/model/student/exceptions/StudentNotFoundException.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/student/EmailTest.java
  src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
Labels: type.Task, priority.High

#318 Return specific error message for duplicated fields in edit_s command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java
Labels: priority.High, severity.High, alpha-bug

#319 Add NFRs based on project constraints
  docs/DeveloperGuide.md
Labels: type.Documentation

#322 Update name constraints
  docs/UserGuide.md
  src/main/java/seedu/address/model/student/Name.java
Labels: priority.High, alpha-bug, type.Documentation

#324 Add test steps
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java
Labels: type.Documentation

#331 Add edit group feature
  docs/UserGuide.md
  docs/images/screenshots/edit_g.png
Labels: type.Documentation

#330 Fix edit group not updating student's group name
  src/main/java/seedu/address/logic/commands/editcommands/EditGroupCommand.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#336 Documentation changes and bug fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskAllGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/markcommands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/findcommands/FindStudentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
Labels: type.Bug, priority.High, alpha-bug, type.Documentation

#340 Add code ownership and PPP
  docs/DeveloperGuide.md
  docs/team/ghos7ie.md
  src/main/java/seedu/address/logic/ListMarkers.java
  src/main/java/seedu/address/logic/commands/addcommands/AddExistingTaskToGroupCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindStudentCommand.java
  src/main/java/seedu/address/logic/commands/findcommands/FindTaskCommand.java
  src/main/java/seedu/address/logic/parser/addcommands/AddExistingTaskToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommands/FindGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommands/FindStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommands/FindTaskCommandParser.java
  src/main/java/seedu/address/model/group/GroupNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/StudentMatchesQueryPredicate.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/FindStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/FindGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/model/group/GroupNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/StudentMatchesKeywordPredicateTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/model/task/StatusTest.java
  src/test/java/seedu/address/model/task/TaskNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskNameTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#343 Update User Guide
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: severity.Low, type.Documentation, fixable.Yes

#409 Updates on DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation, pe-d

#413 Add use cases in DG
  docs/DeveloperGuide.md
Labels: type.Documentation, pe-d

#410 Add note on maximum supported number for Group Name
  docs/UserGuide.md
Labels: priority.High, type.Documentation, fixable.Yes, pe-d

#411 Add in explanation for editing a group
  docs/UserGuide.md
Labels: priority.High, type.Documentation, pe-d

#412 Improve layout of model class diagram
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation, pe-d

#417 Add where to get index for commands that use index
  docs/UserGuide.md
Labels: type.Documentation, pe-d

#421 Update NFR on number of entities app can support and add class diagram
  docs/DeveloperGuide.md
  docs/diagrams/EntityClassDiagram.puml
Labels: type.Documentation

#418 Fix bug for not throwing error message for duplicated email
  src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java
Labels: pe-d

#424 Extraneous parameter check removal
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/addcommands/AddExistingTaskToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddStudentToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddTaskToAllGroupsCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommands/AddTaskToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteStudentFromGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteTaskForAllGroupsCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommands/DeleteTaskFromGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditTaskAllGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommands/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommands/FindGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommands/FindStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommands/FindTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/listcommands/ListTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/markcommands/MarkTaskCommandParser.java
Labels: type.Enhancement, type.Documentation, pe-d

#414 Fix overdue pending mistakes
  src/main/java/seedu/address/model/task/Task.java
Labels: type.Bug

#425 Fix DG bugs and add implemenation for EditTask
  docs/DeveloperGuide.md
  docs/diagrams/EditTaskCommandAD.puml
  docs/diagrams/EditTaskCommandSequence.puml
Labels: type.Documentation

#430 Fix edit task bug
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskAllGroupCommand.java
Labels: type.Bug

#431 Fix group does not exist bug
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteTaskFromGroupCommand.java
  src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java
Labels: type.Bug

#437 V1.6 prep
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/task/Task.java
Labels: type.Bug, severity.High

#438 V1.6 prep
  docs/UserGuide.md
Labels: type.Documentation

#440 Update DG and add exception handling for group numbers that exceed MAX_INT
  docs/DeveloperGuide.md
  docs/diagrams/AddStudentSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/group/GroupName.java
Labels: type.Bug, type.Documentation

#442 Fix issues with typo etc.
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation
